sudo: false
language: generic
os: osx

stages:
  - build

jobs:
   include:
     - stage: build
       script:
         - wget --retry-connrefused --waitretry=1 -O /tmp/nix-install https://nixos.org/releases/nix/nix-2.3.1/install
         - yes | sh /tmp/nix-install
         - . /Users/travis/.nix-profile/etc/profile.d/nix.sh
         - nix build -f . haskell-ide-engine.components.exes.hie
